baseURL: https://lsschmitz.netlify.app
languageCode: en-us
title: lucasschmitz
theme: personal-web
copyright:
googleAnalytics: ''
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
params:
  accentColor: '#1921fd'
  assets:
    customCSS: ''
    favicon: ''
  breadcrumb: yes
  contact:
    email: 'mailto:lsschmitz@uc.cl'
    text: 'Contact me'
  intro:
    main: 'Lucas Schmitz'
    sub: M.A Economics
  main:
    latestPublishHeader: My Latest Project
  mainSections: portfolio
  notFound:
    gopher: /images/gopher.png
    h1: Sorry!
    p: It seems that this page doesn't exist.
  sections:
    portfolio: project
    post: article
  sidebar:
    backgroundImage: ''
    gradientOverlay: ''
    logo: 'images/lucas.png'
  social:
    codepen: 
    facebook: 
    github: https://github.com/
    gitlab: 
    instagram: 
    keybase: 
    linkedin: https://www.linkedin.com/in/
    medium: 
    twitter: https://twitter.com/lsschmitz2
    youtube: 
taxonomies:
  design: designs
  tech: techs
blackfriday:
  hrefTargetBlank: yes
menu:
  main:
    - identifier: about
      name: About
      title: About section
      url: /about/
      weight: -120
    - identifier: CV
      name: CV
      title: CV
      url: /cv/
      weight: -110
    - identifier: Research
      name: Research
      title: Resarch
      url: /post/
      weight: -100
      
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
privacy:
  googleAnalytics:
    anonymizeIP: yes
    disable: yes
    respectDoNotTrack: yes
    useSessionStorage: no
  twitter:
    disable: no
    enableDNT: yes
    simple: no
markup:
  goldmark:
    renderer:
      unsafe: yes
